import Head from "next/head";
import {
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import devscott from "../public/devscott.jpg"
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">byscott</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://acrobat.adobe.com/id/urn:aaid:sc:US:81ee833f-0756-4805-b8fb-fd4500ae7a6c"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Scott Davis
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Systems Administration - Cybersecurity - Application Development.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer (open to work) providing services for all your needs. Join me down below and let's get going!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/scottdaviscyberpro/" target="_blank" rel="noopener noreferrer">
                <AiFillLinkedin />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={devscott} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer:</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Through my education at 
              <span className="text-teal-500"> Bellevue College </span>
              and <span className="text-teal-500">Everett Community College </span>
              I gained hands on experience.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I can provide a wide range of services, including
              programming, pentesting, and systems adminstration.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Systems Administration
              </h3>
              <p className="py-2">
                Design and manage network infrastructure.
              </p>
              <h4 className="py-4 text-teal-600">Proficiencies:</h4>
              <p className="text-gray-800 py-1">AWS, GCP, Azure, Digital Ocean</p>
              <p className="text-gray-800 py-1">Cisco</p>
              <p className="text-gray-800 py-1">VMWare</p>
              <p className="text-gray-800 py-1">Wireshark</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Cybersecurity
              </h3>
              <p className="py-2">
                Is your business safe online?
              </p>
              <h4 className="py-4 text-teal-600">Focus Areas:</h4>
              <p className="text-gray-800 py-1">Penetration Testing</p>
              <p className="text-gray-800 py-1">Application Security</p>
              <p className="text-gray-800 py-1">Computer Forensics</p>
              <p className="text-gray-800 py-1">Incident Response</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Code your dream project</h3>
              <p className="py-2">
              Do you have an idea for your next great website or application? Let's do it!
              </p>
              <h4 className="py-4 text-teal-600">Tools I use:</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">HTML/JavaScript/CSS</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">SQL</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Through my education at 
              <span className="text-teal-500"> Bellevue College </span>
              and <span className="text-teal-500">Everett Community College </span>
              I gained a wide range of skills that show in my many projects.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I can provide a wide range of services, including penetration testing, network design/management,
               and programming/application development.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
          <a href="https://github.com/pawscanthack" target="_blank" rel="noopener noreferrer">
            <AiFillGithub />
          </a>
            </div>
            {/* <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div> */}
        </section>
      </main>
    </div>
  );
}
